name: pomoblue
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.13.0
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/relax_time.jpg
    - assets/images/work_time.jpg
    - assets/images/ready.jpg

  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf
    - family: 8BitsWonder
      fonts:
        - asset: assets/fonts/8BitsWonder.ttf
    - family: Mozart
      fonts:
        - asset: assets/fonts/Mozart.ttf
