name: pomoblue
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.13.0
  rxdart: ^0.22.0
  audioplayers: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/work_time.jpg
    - assets/images/relax_time.jpg
    - assets/images/work_ready.jpg
    - assets/images/work_done.jpg
    - assets/images/chair_ready.jpg
    - assets/images/chair_done.jpg
    - assets/images/travel_ready.jpg
    - assets/images/travel_done.jpg
    - assets/sounds/notification.mp3

  fonts:
    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf
    - family: 8BitsWonder
      fonts:
        - asset: assets/fonts/8BitsWonder.ttf
    - family: Mozart
      fonts:
        - asset: assets/fonts/Mozart.ttf
